language: node_js
cache: npm
notifications:
  email: false
node_js:
  - 10
  - 12
  - 14
  - node
install: npm install
script:
  - npm run validate
  - npx codecov@3
branches:
  only:
    - master
    - beta

jobs:
  include:
    - stage: release
      node_js: 14
      script: kcd-scripts travis-release
      if: fork = false
