name: "Prettier"
on: [pull_request]
jobs:
  tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.10
      - uses: actions/setup-node@v3
        with:
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: pnpm install
      - name: Build NPM packages
        run: pnpm run prerelease
      - name: Run Prettier
        run: pnpm run prettier:ci
